project:
  type: website

website:
  title: "Accessibility of Eldercare Services"
  navbar:
    left:
      - text: "Content"
        menu:
          - text: "Introduction"
            
      - text: "Methodology"
        menu:
          - text: "Methods"
            href: "methodology/methodology.html"
            
      - text: "Results"
        menu: 
          - text: "Discussion"

      - text: "Poster"
        href: nothing.html

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    grid:
      margin-width: 250px
    theme:
      - theme.scss
    css: styles.css
    toc: true
    toc_float: true

editor: visual


